---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx as proxy
  template:
    src: ../templates/proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify:
    - restart nginx

- name: Enable Nginx service
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Open port 3000
  ufw:
    rule: allow
    port: '3000'
    proto: tcp

- name: Configure Nginx as proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx