---
- name: Configure all VMs
  hosts: all
  become: true
  roles:
    - base_setup

- name: Configure proxy server
  hosts: proxy
  become: true
  roles:
    - nginx_proxy

- name: Configure web servers
  hosts: web
  become: true
  roles:
    - nginx_web